name: Create Labels

on:
    push:
        branches:
            - main

jobs:
    create-labels:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Labels CleanUp
              uses: actions/github-script@v6
              with:
                  script: |
                      const labelsToDeleteEnglish = [
                        'documentation',
                        'bug',
                        'request',
                        'rejection',
                        'feature',
                        'warning',
                        'invalid',
                        'question',
                        'duplicate',
                        'enhancement',
                        'good first issue',
                        'help wanted'
                      ];

                      for (const label of labelsToDeleteEnglish) {
                        const existingLabel = await github.rest.issues.getLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label
                        }).catch(() => null);

                        if (existingLabel) {
                          console.log(`Label "${label}" already exists. deleting...`);
                          await github.rest.issues.deleteLabel({
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            name: label,
                          });
                          continue;
                        }

                        console.log(`Label "${label}" does not exist. Skiping...`);
                      }

            - name: Create and Update labels With English
              uses: actions/github-script@v6
              with:
                  script: |
                      const labelsToUpdateEnglish = [
                        { name: 'Docment', color: '2196f3', description: 'Used to create, update and delete documents' },
                        { name: 'Bug', color: 'f44336', description: 'Contents related to bugs' },
                        { name: 'Request', color: '03a9f4', description: 'Request new features and improvements' },
                        { name: 'Rejection', color: 'FFFFFF', description: 'Reject the contents of the Issues' },
                        { name: 'Feature', color: '4caf50', description: 'Contents about new features' },
                        { name: 'Warning', color: 'ffeb3b', description: 'Content related to precautions' },
                        { name: 'Invalid', color: '8bc34a', description: 'Invalid pull request or Issues content' },
                        { name: 'Question', color: '9c27b0', description: 'Questions about specifications and features' },
                        { name: 'Duplication', color: '9e9e9e', description: 'Duplication of Issues content' }
                      ];

                      for (const label of labelsToUpdateEnglish) {
                        const existingLabel = await github.rest.issues.getLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label.name
                        }).catch(() => null);

                        if (existingLabel) {
                          console.log(`Label "${label.name}" already exists. Skiping...`);
                          continue;
                        }

                        console.log(`Label "${label.name}" does not exist. Creating...`);
                        await github.rest.issues.createLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label.name,
                          color: label.color,
                          description: label.description
                        });
                      }

            - name: Create labels With Japanese
              uses: actions/github-script@v6
              with:
                  script: |
                      const labelsToUpdateJapanese = [
                        { name: 'ドキュメント', color: '2196f3', description: 'ドキュメントに関する内容' },
                        { name: 'バグ', color: 'f44336', description: 'バグに関する内容' },
                        { name: 'リクエスト', color: '03a9f4', description: '要望に関する内容' },
                        { name: '不採用', color: 'FFFFFF', description: 'Issuesの内容を不採用にする場合' },
                        { name: '新機能', color: '4caf50', description: '新機能に関する内容' },
                        { name: '注意', color: 'ffeb3b', description: '注意に関する内容' },
                        { name: '無効', color: '8bc34a', description: 'Issuesが無効な内容' },
                        { name: '質問', color: '9c27b0', description: '質問の関する内容' },
                        { name: '重複', color: '9e9e9e', description: 'Issuesの内容が重複している場合' }
                      ];

                      for (const label of labelsToUpdateJapanese) {
                        const existingLabel = await github.rest.issues.getLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label.name
                        }).catch(() => null);

                        if (existingLabel) {
                          console.log(`既に"${label.name}"が存在する為、スキップします...`);
                          continue;
                        }

                        console.log(`"${label.name}"を作成します...`);
                        await github.rest.issues.createLabel({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          name: label.name,
                          color: label.color,
                          description: label.description
                        });
                      }
