name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        # env: ${{secrets.ENV}}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Web test
              run: npm run test:web

            - name: Worker test
              run: npm run test:worker
